### ISSUE TITLE
[DEP]: Add `websockets >=12.0` support

### ISSUE THREAD

**Issue by jjfantini** [supabase-community/realtime-py#108]
# Feature request

There are quite a few packages that are using the newer versions of websocket which makes supabase-py un-usable for a lot of projects where websockets are used.
I have created an issue to update the dependency in `supabase-py`

## Describe the solution you'd like

An updated dependency of `websockets >=12.0`

**Comment by silentworks** [comment]
This has been addressed.

**Comment by jjfantini** [comment]
thanks so much!!
