### ISSUE TITLE
Setup Github Actions

### ISSUE THREAD

**Issue by J0** [supabase-community/realtime-py#14]
# Chore

We need a functioning CI checks and tests for this library so that we can ensure everything is working as expected.

**Comment by RizkyRajitha** [comment]
hi @J0  , i would like to work on this issue

**Comment by J0** [comment]
Sure, go for it @RizkyRajitha

**Comment by RizkyRajitha** [comment]
hi @J0 ,

my task is to create test cases and then add GitHub actions .

i am familiar with gh actions so that seems okay , can i have some more details about how to write the tests

thanks

**Comment by J0** [comment]
Hey @RizkyRajitha,

 Apologies for the delay. You can start with the GH actions first -- the test cases can come later -- you can include a blank test or trivial test just to make sure it works

**Comment by RizkyRajitha** [comment]
thanks @J0 , 
i will create a pr .

**Comment by RizkyRajitha** [comment]
hi @RizkyRajitha , 

in gh actions , shall i use `poetry` to install dependencies because  `requirements.txt` file is not available in this repo.

i got gist by referring to this ci file

https://github.com/supabase-community/supabase-py/blob/develop/.github/workflows/ci-python.yml

**Comment by J0** [comment]
Sure, that works. Thanks so much!

**Comment by J0** [comment]
Resolved by #18

**Comment by J0** [comment]
Thanks @RizkyRajitha !
