### ISSUE TITLE
ModuleNotFoundError: No module named 'realtime_py'

### ISSUE THREAD

**Issue by alif-arrizqy** [supabase-community/realtime-py#21]
I have an error on installing module realtime_py, can you help this issue ?

**Comment by PiyushDixit96** [comment]
same error here.

**Comment by alif-arrizqy** [comment]
Hi myfriend,
after I searched, when I installed the Supabase library (pip install supabase) there was already a library for this realtime.
So the previous error was that I also installed this realtime library (pip install realtime).
then the code from my program is fixed to be:

``` python
from realtime_py.connection import Socket

env_path = Path(".") / ".env"
load_dotenv(env_path)

# supabase conf
supabase_id = os.getenv("SUPABASE_ID")
supabase_key = os.getenv("SUPABASE_KEY")


def callback1(payload):
     print(payload.get("record"))


if __name__ == "__main__":
URL = f"wss://{supabase_id}.supabase.co/realtime/v1/websocket?apikey={supabase_key}&vsn=1.0.0"
     s = Socket(URL)
     s.connect()

     channel_1 = s.set_channel("realtime:public:melawai_realtime")
     channel_1.join().on("UPDATE", callback1)
     s.listen()
```

****notes: if you copy this code, please pay attention to the python indent again**

`thank you`

**Comment by PiyushDixit96** [comment]
thanks

**Comment by dreinon** [comment]
This module is now called `realtime`. Therefore, in order to install it, you would use `pip install realtime` or `poetry add realtime` and then it would be imported like `from realtime import ...`.

Hope this helps :) @PiyushDixit96 @alif-arrizqy

**Comment by alif-arrizqy** [comment]
thank you @dreinon :)

**Comment by PiyushDixit96** [comment]
> This module is now called `realtime`. Therefore, in order to install it, you would use `pip install realtime` or `poetry add realtime` and then it would be imported like `from realtime import ...`.
> 
> Hope this helps :) @PiyushDixit96 @alif-arrizqy

yes helpful
