### ISSUE TITLE
AttributeError: module 'typing' has no attribute '_ClassVar'

### ISSUE THREAD

**Issue by PiyushDixit96** [supabase-community/realtime-py#22]
realtime-py==0.1.3
error "AttributeError: module 'typing' has no attribute '_ClassVar'"

**Comment by kavalerov** [comment]
And same problem here...

**Comment by kavalerov** [comment]
Just realised that I never came back on this - I actually have solved the problem by also adding the following: 

```
RUN rm -rf /var/task/dataclasses*
```

At some point I am going to dive deeper into this and understand why `RUN python3.9 -m pip uninstall -y dataclasses` wasn't enough...

**Comment by kavalerov** [comment]
By looking at the current `pyproject.toml` I am actually not sure if this dependency is needed at all. 

https://github.com/supabase-community/realtime-py/blob/4c808b000bfa3384678ad4aaa5e78f99d5ad89be/pyproject.toml#L8 says that the min python version is Python 3.7, and `dataclasses` is only really needed for 3.6. Should we just remove the dependency? 

I have created https://github.com/supabase-community/realtime-py/pull/48 to address this.

**Comment by PiyushDixit96** [comment]
Thanks.
