### ISSUE TITLE
Unnecessary dependency `dataclasses` causing conflict issues with built-in module `dataclasses`.

### ISSUE THREAD

**Issue by GrandMoff100** [supabase-community/realtime-py#26]
This can be fixed by removing the dataclasses dependency in pyproject.toml. This dependency is unnecessary because dataclasses is a built-in library. Causing the issue in #25 

I am using latest version running on ubuntu-latest.

**Comment by J0** [comment]
@GrandMoff100 Thanks for the catch! We have removed the `dataclasses` dependency.

Closing this issue for now but let us know if you still face issues and we can reopen.
