### ISSUE TITLE
Unable to run `usage.py` successfully

### ISSUE THREAD

**Issue by kalindkaria** [supabase-community/realtime-py#29]
Hi @w3b6x9, @J0, @lionellloh and others,

I tried running the `usage.py` file after modifying the relevant topics served by Phoenix server.
But the value of `channel_obj.joined` is `False` after the `channel_obj.join()` is invoked. I am not sure what's wrong.

Below is the snippet of modified `usage.py`:

```py
from realtime.connection import Socket

def callback1(payload):
    print("Callback 1: ", payload)

def callback2(payload):
    print("Callback 2: ", payload)

url = "ws://localhost:4000/socket/websocket"
s = Socket(url)

s.connect()
s.summary()

channel_1 = s.set_channel("robot:status")
channel_2 = s.set_channel("timer:update")

channel_1.join().on("new_msg", callback1)
channel_2.join().on("new_time", callback2)

print(channel_1.joined)
print(channel_2.joined)

if __name__ == "__main__":
    s.listen()
```

Phoenix Server is running fine with the respective Elixir clients able to send/receive messages with each other.
Moreover, the Phoenix Server output shows the following debug messages when `usage.py` is ran and I believe this states that the python client is able to connect the server.

```elixir
[info] CONNECTED TO PhoenixServerWeb.UserSocket in 41µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V1.JSONSerializer
  Parameters: %{}
[info] JOINED robot:status in 17µs
  Parameters: %{}
[info] JOINED timer:update in 7µs
  Parameters: %{}
```

Kindly highlight what I could have missed here.
Thanks in advance.

**Comment by kalindkaria** [comment]
Sorry to bother you, it was an error from my end.
Thanks for your time.

**Comment by J0** [comment]
Hey @kalindkaria,

Sorry for the delayed reply. Thank you for taking the time to compose the error! We're glad you figured the issue out but do feel free to let us know if you run into any further errors :)
Joel
