### ISSUE TITLE
Unable to get realtime connection to Supabase locally

### ISSUE THREAD

**Issue by JamesLloydPartington** [supabase-community/realtime-py#40]
I am currently trying to use realtime.connection.Socket() with Supabase locally. I am following this guild (https://supabase.com/docs/guides/local-development). I am using a MacBook Pro with an M1 chip, realtime==0.0.4.

From the Supabase guide, I have run "supabase start" and "docker ps" in the terminal:
<img width="987" alt="Terminal screenshot" src="https://user-images.githubusercontent.com/67102512/176175619-de4b2b3c-f788-44e4-84b1-34f0347684d5.png">

Sample code to run:

```
from realtime.connection import Socket
# local service key
SUPA_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSJ9.vI9obAHOGyVVKa3pD--kJlyxp-Z2zV9UUMAhKpNLAcU"

HOST_PORT = 54321

SUPA_REALTIME_URL = f"wss://localhost:{HOST_PORT}/realtime/v1/websocket?apikey={SUPA_SERVICE_KEY}&vsn=1.0.0"

s = Socket(SUPA_REALTIME_URL)
s.connect()
```

After running this code I get:
<img width="866" alt="Screenshot 2022-06-28 at 13 24 58" src="https://user-images.githubusercontent.com/67102512/176178800-58600ef2-ef3c-4e9f-8643-75ae34009d67.png">

Could this be because of the SUPA_REALTIME_URL being incorrect? I have tried several different HOST_PORT shown in "docker ps" with no success.

**Comment by chitalian** [comment]
@JamesLloydPartington did you ever figure this out?

**Comment by JamesLloydPartington** [comment]
@chitalian  Unfortunately I have not.

**Comment by chitalian** [comment]
oh my gosh @JamesLloydPartington  you might facepalm at this one...
`wss` -> `ws`

**Comment by chitalian** [comment]
however.
I am running into another issue now lol
https://github.com/supabase/realtime/issues/347


But I think you can probably close this issue :)

**Comment by JamesLloydPartington** [comment]
I do remember trying both wws and ws a while back. But neither of those worked. Since you have a new issue open, I'll close this one.

**Comment by JamesLloydPartington** [comment]
I do remember trying both wws and ws a while back. But neither of those worked. Since you have a new issue open, I'll close this one.

**Comment by chitalian** [comment]
@JamesLloydPartington 
> I do remember trying both wws and ws a while back. But neither of those worked. Since you have a new issue open, I'll close this one.

Yeah they are actually going to get it to work here
https://github.com/supabase/cli/pull/594

this should work, I got it to connect successfully. Let me know if you need any help running it locally :) for me it was just doing `ws`
